"use client";

import { useCallback, useEffect, useState } from "react";
import { AdminNavigation } from "../admin-navigation";

type Client = { id: number; name: string; slug: string; subscriptionStatus: string; websiteUrl: string | null; installationStatus: string; plan: string; total: number; published: number; ownerEmail: string };

export function ClientsAdmin({ displayName }: { displayName: string }) {
  const [items, setItems] = useState<Client[]>([]); const [creating, setCreating] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/admin/clients", { cache: "no-store" }); if (response.ok) setItems((await response.json()).items); else setError("Доступ к управлению клиентами не найден."); }, []);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await fetch("/api/admin/clients", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); if (!response.ok) { setError("Проверьте данные: идентификатор должен быть уникальным."); return; } setCreating(false); setError(""); await load(); }
  return <main className="admin-shell"><AdminNavigation active="clients" displayName={displayName}/><section className="admin-main"><header className="admin-head"><div><p>ОПЕРАЦИОННЫЙ ЦЕНТР</p><h1>Магазины</h1></div><button className="admin-primary" onClick={() => setCreating(true)}>＋ Добавить клиента</button></header><div className="client-summary"><article><span>Клиентов</span><strong>{items.length}</strong></article><article><span>Установили виджет</span><strong>{items.filter(item => item.installationStatus === "connected").length}</strong></article><article><span>Моделей опубликовано</span><strong>{items.reduce((sum, item) => sum + item.published, 0)}</strong></article></div><div className="clients-grid">{items.map(item => <article key={item.id}><header><div><b>{item.name}</b><span>{item.slug}</span></div><i className={item.installationStatus === "connected" ? "online" : ""}/></header><dl><div><dt>Владелец</dt><dd>{item.ownerEmail || "Не назначен"}</dd></div><div><dt>Каталог</dt><dd>{item.published} из {item.total} в AR</dd></div><div><dt>Тариф</dt><dd>{item.plan} · {item.subscriptionStatus}</dd></div></dl><footer><a href={`/admin/catalog?shop=${encodeURIComponent(item.slug)}`}>Каталог</a><a href={`/admin/setup?shop=${encodeURIComponent(item.slug)}`}>Подключение →</a></footer></article>)}</div>{error && <p className="admin-error">{error}</p>}</section>{creating && <div className="edit-backdrop" role="presentation"><form className="edit-model" onSubmit={create}><header><div><p>НОВЫЙ КЛИЕНТ</p><h2>Добавить магазин</h2></div><button type="button" onClick={() => setCreating(false)}>×</button></header><label>Название<input name="name" required placeholder="NORDform"/></label><label>Идентификатор<input name="slug" required pattern="[a-z0-9-]{3,60}" placeholder="nordform"/></label><label>Email владельца<input name="ownerEmail" type="email" required placeholder="owner@store.com"/></label><label>Сайт<input name="websiteUrl" type="url" placeholder="https://store.com"/></label><p>Когда владелец войдёт с этим email, магазин автоматически появится в его кабинете.</p><button className="save-model">Создать магазин</button></form></div>}</main>;
}
