"use client";

import { useCallback, useEffect, useState } from "react";
import { AdminNavigation } from "../admin-navigation";

type Entry = { id: number; email: string; role: string; expiresAt?: string | null };
const roleNames: Record<string, string> = { owner: "Владелец", editor: "Редактор", analyst: "Аналитик", operator: "Администратор MIRRAI" };

export function TeamAdmin({ displayName, shopSlug }: { displayName: string; shopSlug: string }) {
  const [members, setMembers] = useState<Entry[]>([]); const [invites, setInvites] = useState<Entry[]>([]); const [shopName, setShopName] = useState(""); const [error, setError] = useState(""); const [link, setLink] = useState("");
  const load = useCallback(async () => { if (!shopSlug) return; const response = await fetch(`/api/admin/members?shop=${encodeURIComponent(shopSlug)}`, { cache: "no-store" }); if (!response.ok) { setError(response.status === 403 ? "У вас нет права управлять командой этого магазина." : "Не удалось загрузить команду."); return; } const data = await response.json(); setMembers(data.members); setInvites(data.invites); setShopName(data.shop.name); }, [shopSlug]);
  useEffect(() => { const pending = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(pending); }, [load]);
  async function invite(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/admin/members", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ shop: shopSlug, email: form.get("email"), role: form.get("role") }) }); const result = await response.json().catch(() => ({})); if (!response.ok) { setError(result.error === "already_member" ? "Этот пользователь уже в команде." : "Не удалось создать приглашение."); return; } setLink(new URL(result.invitationUrl, window.location.origin).toString()); event.currentTarget.reset(); await load(); }
  async function remove(kind: "member" | "invite", id: number) { const response = await fetch("/api/admin/members", { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ shop: shopSlug, [kind === "member" ? "memberId" : "inviteId"]: id }) }); if (response.ok) await load(); else setError("Не удалось удалить доступ."); }
  return <main className="admin-shell"><AdminNavigation active="team" displayName={displayName} shopSlug={shopSlug}/><section className="admin-main"><header className="admin-head"><div><p>БЕЗОПАСНОСТЬ</p><h1>Команда и доступ</h1><span>{shopName || "Выберите магазин"}</span></div></header>{shopSlug && <><section className="team-layout"><form className="team-invite" onSubmit={invite}><h2>Пригласить сотрудника</h2><label>Рабочая почта<input name="email" type="email" required placeholder="manager@store.md"/></label><label>Уровень доступа<select name="role" defaultValue="editor"><option value="editor">Редактор — каталог и модели</option><option value="analyst">Аналитик — только просмотр</option></select></label><button className="admin-primary">Создать ссылку</button><p>Ссылка одноразовая и действует 7 дней.</p></form><section className="team-list"><h2>Текущая команда</h2>{members.map(member => <article key={member.id}><div><b>{member.email}</b><span>{roleNames[member.role] ?? member.role}</span></div>{member.role !== "owner" && <button type="button" onClick={() => void remove("member", member.id)}>Отозвать</button>}</article>)}{invites.map(invite => <article className="pending" key={`invite-${invite.id}`}><div><b>{invite.email}</b><span>Ожидает · {roleNames[invite.role] ?? invite.role}</span></div><button type="button" onClick={() => void remove("invite", invite.id)}>Отменить</button></article>)}</section></section>{link && <section className="invite-result"><div><b>Приглашение готово</b><span>Скопируйте и отправьте ссылку сотруднику.</span></div><input readOnly value={link}/><button type="button" onClick={() => void navigator.clipboard.writeText(link)}>Копировать</button></section>}</>}{error && <p className="admin-error">{error}</p>}</section></main>;
}
