"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AdminNavigation } from "../admin-navigation";

type ModelStatus = "missing" | "queued" | "processing" | "review" | "ready" | "published" | "failed";
type CatalogItem = { id: number; sku: string; name: string; category: string; price: string; material: string; widthCm: number | null; heightCm: number | null; depthCm: number | null; sourceUrl: string | null; imageUrls: string[]; sourceUpdatedAt: string | null; model: { status: ModelStatus; glbUrl: string | null; usdzUrl: string | null; validationMessage: string | null; qualityScore: number | null } };
type CatalogData = { shop: { name: string; slug: string; subscriptionStatus: string; catalogSourceType: string; catalogSyncStatus: string; catalogSyncedAt: string | null; catalogSyncMessage: string | null }; counts: { total: number; ready: number; processing: number; review: number; missing: number; failed: number; withPhotos: number }; items: CatalogItem[] };
type GenerationData = { serviceConfigured: boolean; items: { job: { id: string; productId: number; status: string; errorMessage: string | null }; sku: string; name: string }[] };

const statusLabels: Record<ModelStatus, string> = { missing: "Нет модели", queued: "В очереди", processing: "Создаётся", review: "Нужна проверка", ready: "Готова", published: "Опубликована", failed: "Ошибка" };
const filterOptions = [{ value: "all", label: "Все" }, { value: "published", label: "Опубликованы" }, { value: "processing", label: "В работе" }, { value: "review", label: "На проверке" }, { value: "missing", label: "Без модели" }, { value: "failed", label: "Ошибки" }];

export function CatalogAdmin({ displayName, shopSlug }: { displayName: string; shopSlug: string }) {
  const [data, setData] = useState<CatalogData | null>(null);
  const [error, setError] = useState("");
  const [filter, setFilter] = useState("all");
  const [query, setQuery] = useState("");
  const [editing, setEditing] = useState<CatalogItem | null>(null);
  const [saving, setSaving] = useState(false);
  const [importing, setImporting] = useState(false);
  const [syncing, setSyncing] = useState(false);
  const [uploading, setUploading] = useState("");
  const [assetUrls, setAssetUrls] = useState<{ glb?: string; usdz?: string }>({});
  const [generation, setGeneration] = useState<GenerationData | null>(null);
  const [selected, setSelected] = useState<Set<number>>(new Set());
  const [queueing, setQueueing] = useState(false);

  const load = useCallback(async () => {
    try { const response = await fetch(`/api/admin/catalog${shopSlug ? `?shop=${encodeURIComponent(shopSlug)}` : ""}`); if (!response.ok) throw new Error(); const catalog = await response.json() as CatalogData; setData(catalog); setSelected(current => current.size ? current : new Set(catalog.items.filter(item => item.imageUrls.length && item.widthCm && item.heightCm).slice(0, 4).map(item => item.id))); const jobs = await fetch(`/api/admin/generation${shopSlug ? `?shop=${encodeURIComponent(shopSlug)}` : ""}`); if (jobs.ok) setGeneration(await jobs.json()); setError(""); }
    catch { setError("Не удалось загрузить каталог. Обновите страницу."); }
  }, [shopSlug]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);

  const visible = useMemo(() => (data?.items ?? []).filter(item => {
    const statusMatch = filter === "all" || (filter === "processing" ? ["queued", "processing"].includes(item.model.status) : item.model.status === filter);
    const text = `${item.name} ${item.sku} ${item.category}`.toLowerCase();
    return statusMatch && text.includes(query.trim().toLowerCase());
  }), [data, filter, query]);

  async function saveModel(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!editing) return;
    const form = new FormData(event.currentTarget); setSaving(true); setError("");
    const response = await fetch("/api/admin/catalog", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ shop: data?.shop.slug, productId: editing.id, status: form.get("status"), glbUrl: form.get("glbUrl"), usdzUrl: form.get("usdzUrl"), validationMessage: form.get("validationMessage") }) });
    if (!response.ok) { const result = await response.json().catch(() => ({})); setError(result.error === "glb_required_for_publish" ? "Для публикации нужен GLB-файл." : "Изменения не сохранены."); setSaving(false); return; }
    setEditing(null); setSaving(false); await load();
  }

  async function importCatalog(file?: File) { if (!file || !data) return; setImporting(true); setError(""); const form = new FormData(); form.append("file", file); form.append("shop", data.shop.slug); const response = await fetch("/api/admin/catalog/import", { method: "POST", body: form }); const result = await response.json().catch(() => ({})); if (!response.ok) setError(result.error === "headers_required" ? "В CSV обязательны колонки SKU и name/название." : "Не удалось импортировать CSV."); else setError(result.errors?.length ? `Импортировано: ${result.imported}. ${result.errors[0]}` : ""); setImporting(false); await load(); }
  async function syncCatalog() { if (!data || syncing) return; setSyncing(true); setError(""); let offset: number | null = 0; try { while (offset !== null) { const response = await fetch("/api/admin/catalog/sync", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ shop: data.shop.slug, offset }) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error === "source_unreachable" ? "Сайт магазина недоступен по защищённому HTTPS. Для hugge.md нужно продлить сертификат." : "Не удалось синхронизировать каталог сайта."); offset = result.nextOffset; } await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Не удалось синхронизировать каталог сайта."); } finally { setSyncing(false); } }
  async function uploadAsset(file: File | undefined, kind: "glb" | "usdz") { if (!file || !editing || !data) return; setUploading(kind); const form = new FormData(); form.append("file", file); form.append("kind", kind); form.append("productId", String(editing.id)); form.append("shop", data.shop.slug); const response = await fetch("/api/admin/assets", { method: "POST", body: form }); const result = await response.json().catch(() => ({})); if (response.ok) setAssetUrls(current => ({ ...current, [kind]: result.url })); else setError("Файл не загружен. Допустимы GLB/USDZ до 50 МБ."); setUploading(""); }
  async function generationAction(action: "enqueue" | "run") { if (!data || queueing) return; setQueueing(true); setError(""); const response = await fetch("/api/admin/generation", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ shop: data.shop.slug, action, productIds: [...selected] }) }); const result = await response.json().catch(() => ({})); if (!response.ok) setError(result.error === "service_not_configured" ? "Очередь готова. Для запуска подключите Hugging Face ZeroGPU или собственный 3D-сервер." : "Не удалось обновить очередь генерации."); else if (result.blocked) setError("Товары добавлены, но запуск заблокирован: продлите сертификат hugge.md и подключите ZeroGPU."); setQueueing(false); await load(); }

  return <main className="admin-shell">
    <AdminNavigation active="catalog" displayName={displayName} shopSlug={shopSlug}/>
    <section className="admin-main" id="catalog">
      <header className="admin-head"><div><p>КАТАЛОГ / 3D-ПОКРЫТИЕ</p><h1>Модели товаров</h1></div><div className="admin-head-actions">{data?.shop.catalogSourceType === "sitemap" && <button className="admin-primary" disabled={syncing} onClick={() => void syncCatalog()}>{syncing ? "Синхронизируем…" : "Обновить с сайта"}</button>}<a href="/mirrai-catalog-template.csv" download>Шаблон CSV</a><label className="admin-primary">{importing ? "Импортируем…" : "Импорт CSV"}<input type="file" accept=".csv,text/csv" disabled={importing} onChange={event => void importCatalog(event.target.files?.[0])}/></label><a href="/demo-store">Открыть демо ↗</a></div></header>
      {data ? <><div className="admin-shop"><div><i/><span><strong>{data.shop.name}</strong><small>shopId: {data.shop.slug} · {data.shop.catalogSyncMessage ?? "ручной каталог"}</small></span></div><b className={`subscription ${data.shop.catalogSyncStatus === "ready" ? "active" : data.shop.subscriptionStatus}`}>{data.shop.catalogSyncStatus === "blocked" ? "Источник недоступен" : data.shop.subscriptionStatus === "active" ? "Подписка активна" : data.shop.subscriptionStatus}</b></div>
      <div className="admin-stats"><article><span>Всего SKU</span><strong>{data.counts.total}</strong></article><article><span>Фото найдено</span><strong>{data.counts.withPhotos}</strong></article><article><span>Готовы к AR</span><strong>{data.counts.ready}</strong></article><article><span>В обработке</span><strong>{data.counts.processing}</strong></article><article><span>Без модели</span><strong>{data.counts.missing}</strong></article></div>
      <div className="coverage"><span><i style={{ width: `${data.counts.total ? data.counts.ready / data.counts.total * 100 : 0}%` }}/></span><p><strong>{data.counts.total ? Math.round(data.counts.ready / data.counts.total * 100) : 0}%</strong> каталога доступно покупателям в AR</p></div>
      <section className="generation-queue"><div><p>ПАКЕТНАЯ ГЕНЕРАЦИЯ 3D</p><h2>Подготовить модели из фотографий</h2><span>{generation?.serviceConfigured ? "ZeroGPU или 3D-сервер подключён. Сначала создаём GLB, затем проверяем масштаб и материалы." : "Очередь работает, но генератор пока не подключён. Товары сохранятся и не будут ошибочно помечены готовыми."}</span></div><dl><div><dt>Выбрано</dt><dd>{selected.size}</dd></div><div><dt>В очереди</dt><dd>{generation?.items.filter(item => ["queued", "processing", "blocked"].includes(item.job.status)).length ?? 0}</dd></div><div><dt>На проверке</dt><dd>{generation?.items.filter(item => item.job.status === "review").length ?? 0}</dd></div></dl><div><button disabled={!selected.size || queueing} onClick={() => void generationAction("enqueue")}>{queueing ? "Сохраняем…" : "Добавить выбранные"}</button><button disabled={!generation?.serviceConfigured || queueing} onClick={() => void generationAction("run")}>Запустить / проверить</button></div></section>
      <div className="admin-tools"><label><span>⌕</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Поиск по товару или SKU"/></label><div>{filterOptions.map(option => <button key={option.value} className={filter === option.value ? "active" : ""} onClick={() => setFilter(option.value)}>{option.label}</button>)}</div></div>
      <div className="catalog-table"><div className="catalog-row catalog-header"><span/><span>Товар</span><span>SKU</span><span>Габариты</span><span>Файлы</span><span>Статус</span><span/></div>{visible.map(item => <div className="catalog-row" key={item.id}><span><input className="product-select" type="checkbox" aria-label={`Выбрать ${item.name}`} checked={selected.has(item.id)} disabled={!item.imageUrls.length} onChange={event => setSelected(current => { const next = new Set(current); if (event.target.checked) next.add(item.id); else next.delete(item.id); return next; })}/></span><span className="admin-product"><i style={item.imageUrls[0] ? { backgroundImage: `url(${item.imageUrls[0]})` } : undefined}/><b>{item.name}<small>{item.category}{item.imageUrls.length ? ` · ${item.imageUrls.length} фото` : ""}{item.material ? ` · ${item.material}` : ""}</small></b></span><span className="sku">{item.sku}</span><span>{item.widthCm && item.depthCm && item.heightCm ? `${item.widthCm} × ${item.depthCm} × ${item.heightCm}` : <em>Не указаны</em>}</span><span className="asset-flags"><b className={item.imageUrls.length ? "ready" : ""}>PHOTO</b><b className={item.model.glbUrl ? "ready" : ""}>GLB</b><b className={item.model.usdzUrl ? "ready" : ""}>USDZ</b></span><span><b className={`status status-${item.model.status}`}><i/>{statusLabels[item.model.status]}</b><small className="validation">{item.model.validationMessage}</small></span><span><button className="row-action" onClick={() => { setEditing(item); setAssetUrls({}); }}>Изменить</button></span></div>)}</div></> : <div className="admin-loading">{error || "Загружаем каталог…"}</div>}
      {error && data && <p className="admin-error">{error}</p>}
    </section>
    {editing && <div className="edit-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) setEditing(null); }}><form className="edit-model" onSubmit={saveModel}><header><div><p>МОДЕЛЬ ТОВАРА</p><h2>{editing.name}</h2><small>{editing.sku}</small></div><button type="button" onClick={() => setEditing(null)}>×</button></header>{editing.imageUrls.length > 0 && <div className="source-gallery">{editing.imageUrls.slice(0, 4).map(url => <i style={{ backgroundImage: `url(${url})` }} key={url}/>)}<span>{editing.imageUrls.length} фото с сайта{editing.sourceUrl && <a href={editing.sourceUrl} target="_blank" rel="noreferrer">Открыть товар ↗</a>}</span></div>}<label>Статус<select name="status" defaultValue={editing.model.status}>{Object.entries(statusLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><div className="asset-upload-grid"><label>Загрузить GLB<input type="file" accept=".glb,model/gltf-binary" onChange={event => void uploadAsset(event.target.files?.[0], "glb")}/><span>{uploading === "glb" ? "Загрузка…" : assetUrls.glb ? "Загружен ✓" : "До 50 МБ"}</span></label><label>Загрузить USDZ<input type="file" accept=".usdz,model/vnd.usdz+zip" onChange={event => void uploadAsset(event.target.files?.[0], "usdz")}/><span>{uploading === "usdz" ? "Загрузка…" : assetUrls.usdz ? "Загружен ✓" : "Для iPhone"}</span></label></div><label>GLB URL<input name="glbUrl" value={assetUrls.glb ?? editing.model.glbUrl ?? ""} onChange={event => setAssetUrls(current => ({ ...current, glb: event.target.value }))} placeholder="https://cdn…/model.glb"/></label><label>USDZ URL для iPhone<input name="usdzUrl" value={assetUrls.usdz ?? editing.model.usdzUrl ?? ""} onChange={event => setAssetUrls(current => ({ ...current, usdz: event.target.value }))} placeholder="https://cdn…/model.usdz"/></label><label>Результат проверки<textarea name="validationMessage" defaultValue={editing.model.validationMessage ?? ""}/></label><p>После загрузки модель получает статус «Нужна проверка». Публикуйте её только после проверки масштаба и материалов.</p><button className="save-model" disabled={saving || Boolean(uploading)}>{saving ? "Сохраняем…" : "Сохранить модель"}</button></form></div>}
  </main>;
}
